#���ڵ�
#Ӧ�����Ƽ���֤�˺�
spring:
  application:
    name: eureka

  security:
    user:
      name: root
      password: root
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    #�ر����ұ���
    enable-self-preservation: false
    #������ʱ��
    eviction-interval-timer-in-ms: 5000
logging:
  level:
    root: info
---  #����б�ܱ�ʾ������,ʹ֮��Ч��Ҫ�������в���   VMoptions   -Dspring.profiles.active=7900
spring:
  profiles: 7900
server:
  port: 7900
eureka:
  instance:
    #    prefer-ip-address: true
    #    ip-address: 192.168.0.103
    hostname: eureka-7900
  client:
    service-url:
      defaultZone: http://root:root@localhost:7900/eureka/


